In [5]:
import numpy as np

In [ ]:
A = np.array([[1,3],[-1,1]])
B = np.array([[1,2],[2,0]])
print(A.dot(B))

[[ 7  2]
 [ 1 -2]]


In [ ]:
A = np.array( [[5,1,4], 
               [1,7,-1]] )
b = np.array([[3],
              [1],
              [-6]])
print(A.dot(b))

[[-8]
 [16]]


In [20]:
A = np.array([[complex(0,1),complex(0,1),-1],
              [complex(0,1),complex(0,1),complex(0,1)],
              [1,complex(0,1),complex(0,1)]])

print(np.linalg.matrix_rank(A))

3


In [19]:
A = np.array([[8,1],[1,0]])
print(np.linalg.inv(A))

[[ 0.  1.]
 [ 1. -8.]]


In [ ]:
A = np.array([[1,3,1],
              [3,0,-2],
              [1,-1,-3]])
print(np.linalg.det(A))

16.000000000000007


In [27]:
A = np.array([[3,0,0],
              [-3,3,0],
              [-3,-4,-1]])
B = np.array([[3,-2,3],
              [0,3,3],
              [0,0,2]])

print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.det(A.dot(B)))
print(np.linalg.det(np.linalg.inv(A)))

-9.000000000000002
18.000000000000004
-162.00000000000009
-0.11111111111111115


In [29]:
A = np.array([[1,2,-2],
              [-2,1,-2],
              [-1,-4,2]])
B = np.array([[2,-2,2],
              [2,3,6],
              [1,4,-1]])
print(A+B)
print(np.linalg.det(A+B))

[[3 0 0]
 [0 4 4]
 [0 0 1]]
12.0


In [49]:
x = 0
a = np.array([[0],
              [7],
              [0]])
b = np.array([[1],
              [5],
              [-4]])
c = np.array([[7],
              [2],
              [x]])
T = np.concatenate((a, b, c), axis = 1)

for i in range(5):
    print(T)
    print(np.linalg.det(T))
    x=x+1



[[ 0  1  7]
 [ 7  5  2]
 [ 0 -4  0]]
-195.99999999999991
[[ 0  1  7]
 [ 7  5  2]
 [ 0 -4  0]]
-195.99999999999991
[[ 0  1  7]
 [ 7  5  2]
 [ 0 -4  0]]
-195.99999999999991
[[ 0  1  7]
 [ 7  5  2]
 [ 0 -4  0]]
-195.99999999999991
[[ 0  1  7]
 [ 7  5  2]
 [ 0 -4  0]]
-195.99999999999991
